Vagrant.configure("2") do |config|

  config.vm.define "dhcp_server" do |dhcp_server|

    dhcp_server.vm.box = "tvlooy/openbsd-7.4-amd64"
    dhcp_server.vm.box_version = "20231929"

    dhcp_server.vm.synced_folder ".", "/vagrant", disabled: true

    dhcp_server.vm.hostname = "dhcpserver"

    dhcp_server.vm.network "private_network", ip: "192.168.42.0",
      virtualbox__intnet: "administration"
    
    dhcp_server.vm.network "private_network", ip: "192.168.42.64",
      virtualbox__intnet: "server"

    dhcp_server.vm.network "private_network", ip: "192.168.42.128",
      virtualbox__intnet: "employee"


    dhcp_server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "dhcp_server"
      vb.memory = 2048
      vb.cpus = 2
      

    end

    

    # dhcp_server.vm.provision "ansible" do |ansible|

    #   ansible.playbook = "vm-config.yml"  

    # end


  end



end
