Vagrant.configure("2") do |config|

  config.vm.define "webserver" do |webserver|

    webserver.vm.box = "freebsd/FreeBSD-13.0-STABLE"

    webserver.vm.synced_folder ".", "/vagrant", disabled: true

    #webserver.vm.network "forwarded_port", guest: 22, host: "2235", host_ip: "127.0.0.1"

    webserver.vm.hostname = "webserver"

    webserver.vm.network "private_network", virtualbox__intnet: "server"

    webserver.vm.provider "virtualbox" do |vb|

      #vb.customize ["modifyvm", :id, "--nic1", "intnet"]
      vb.gui = false
      vb.name = "webserver"
      vb.memory = 2048
      vb.cpus = 2

    end
    
    webserver.vm.provision "ansible" do |ansible|

      ansible.playbook = "vm-config.yml"  

    end

  end

end
