- name: Configure webserver 
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: Install nginx
      include_tasks: 
        file: ./tasks/install_nginx.yml

    - name: Install mysql
      include_tasks:
        file: ./tasks/install_mysql.yml
   
    - name: Install php
      include_tasks:
        file: ./tasks/install_php80.yml

    - name: Copy rc.conf for enable
      include_tasks:
        file: ./tasks/copy_rcconf_to_host.yml

    - name: Start mysql
      ansible.builtin.command: service mysql-server start
      ignore_errors: true

    - name: Start nginx
      ansible.builtin.command: service nginx start
      ignore_errors: true

    - name: Start php-fpm
      ansible.builtin.command: service php-fpm start
      ignore_errors: true
   
    - name: Create database
      include_tasks:
        file: ./tasks/create_mysql_database.yml
   
    - name: Create mysql user
      include_tasks:
        file: ./tasks/create_mysql_user.yml
   
    - name: Copy sql file
      include_tasks:
        file: ./tasks/copy_nsa501_to_host.yml    
   
    - name: Fill datas
      include_tasks:
        file: ./tasks/add_data.yml
   
    - name: Copy php file
      include_tasks:
        file: ./tasks/copy_dataphp_to_host.yml

    - name: Change nginx.conf
      include_tasks:
        file: ./tasks/modify_nginxconf.yml
    
    - name: Restart php-fpm
      ansible.builtin.command: service php-fpm restart
    
    - name: Restart nginx
      ansible.builtin.command: service nginx restart
