Vagrant.configure("2") do |config|


  config.vm.define "webserver" do |webserver|

    webserver.vm.box = "freebsd/FreeBSD-13.0-STABLE"

    # webserver.ssh.shell = "/bin/ksh"

    webserver.vm.synced_folder ".", "/vagrant", disabled: true

    webserver.vm.hostname = "webserver"

    webserver.vm.network "private_network", type: "dhcp", virtualbox__intnet: "server"

    # webserver.vm.network "forwarded_port", guest: 22, host:2200, disabled: true

    webserver.vm.provider "virtualbox" do |vb|

      # vb.customize ["modifyvm", :id, "--nic1", "none"]
      vb.gui = false
      vb.name = "webserver"
      vb.memory = 2048
      vb.cpus = 2

    end

    webserver.vm.provision "shell", inline: <<-SHELL
      sed -i '' 's/^ifconfig_em1="inet .*"/ifconfig_em1="DHCP"/' /etc/rc.conf
    SHELL
    
    webserver.vm.provision "ansible" do |ansible|
      ansible.playbook = "vm-config.yml"
    
    end
    

 
    

  end

end
